### ISSUE TITLE
Client side build system

### ISSUE THREAD

**Issue by cameronmaske** [cameronmaske/skipper#3]
- [ ] Gulp + builder in fig.yml
- [ ] AngularJS 
- [ ] Bower?

**Comment by Jwpe** [comment]
@cameronmaske is this for building static content for the 'brain' itself? Or a generic 'builder' service?

**Comment by cameronmaske** [comment]
Static content builder for the brain :)—
web: cameronmaske.com
twitter: @cameronmaske
